### ISSUE TITLE
povoamento

### ISSUE THREAD

**Issue by paulos-f** [paulos-f/Banco-2-o-Trabalho-Final#20]
adaptando o povoamento das tabelas

**Comment by paulos-f** [comment]
Inserindo os dados das tabelas:
    
    INSERT INTO cliente (cod_cliente, cpf, nome, sexo, dt_nascimento, dt_cadastro, num_contato, email, endereco) VALUES
    (1, '123.456.789-01', 'Alice Souza', 'F', '1996-05-10', '2021-01-01', '12345678901', 'alice@example.com', 'Rua A, 123'),
    (2, '234.567.890-12', 'Bruno Lima', 'M', '1992-11-20', '2021-02-01', '12345678902', 'bruno@example.com', 'Rua B, 456'),
    (3, '345.678.901-23', 'Carlos Silva', 'M', '1987-08-15', '2021-03-01', '12345678903', 'carlos@example.com', 'Rua C, 789'),
    (4, '456.789.012-34', 'Daniela Araújo', 'F', '1990-12-30', '2021-04-01', '12345678904', 'daniela@example.com', 'Rua D, 101'),
    (5, '567.890.123-45', 'Eduardo Pereira', 'M', '1975-07-25', '2021-05-01', '12345678905', 'eduardo@example.com', 'Rua E, 102'),
    (6, '678.901.234-56', 'Fernanda Costa', 'F', '1998-01-14', '2021-06-01', '12345678906', 'fernanda@example.com', 'Rua F, 103'),
    (7, '789.012.345-67', 'Gabriel Almeida', 'M', '1983-09-05', '2021-07-01', '12345678907', 'gabriel@example.com', 'Rua G, 104'),
    (8, '890.123.456-78', 'Helena Ramos', 'F', '1994-03-22', '2021-08-01', '12345678908', 'helena@example.com', 'Rua H, 105'),
    (9, '901.234.567-89', 'Igor Santos', 'M', '1990-10-12', '2021-09-01', '12345678909', 'igor@example.com', 'Rua I, 106'),
    (10, '012.345.678-90', 'Juliana Oliveira', 'F', '1993-04-02', '2021-10-01', '12345678910', 'juliana@example.com', 'Rua J, 107'),
    (11, '123.456.789-11', 'Kleber Duarte', 'M', '1988-05-16', '2021-11-01', '12345678911', 'kleber@example.com', 'Rua K, 108'),
    (12, '234.567.890-22', 'Lúcia Teixeira', 'F', '1996-06-28', '2021-12-01', '12345678912', 'lucia@example.com', 'Rua L, 109'),
    (13, '345.678.901-33', 'Marcelo Vieira', 'M', '1991-02-18', '2021-01-15', '12345678913', 'marcelo@example.com', 'Rua M, 110'),
    (14, '456.789.012-44', 'Natália Melo', 'F', '1989-07-09', '2021-02-15', '12345678914', 'natalia@example.com', 'Rua N, 111'),
    (15, '567.890.123-55', 'Otávio Rocha', 'M', '1981-03-03', '2021-03-15', '12345678915', 'otavio@example.com', 'Rua O, 112'),
    (16, '678.901.234-66', 'Paula Farias', 'F', '1986-01-11', '2021-04-15', '12345678916', 'paula@example.com', 'Rua P, 113'),
    (17, '789.012.345-77', 'Rafael Borges', 'M', '1984-08-22', '2021-05-15', '12345678917', 'rafael@example.com', 'Rua Q, 114'),
    (18, '890.123.456-88', 'Sabrina Castro', 'F', '1997-11-03', '2021-06-15', '12345678918', 'sabrina@example.com', 'Rua R, 115'),
    (19, '901.234.567-99', 'Tereza Gomes', 'F', '1982-06-19', '2021-01-19', '12345678919', 'tereza@example.com', 'Rua S, 116'),
    (20, '012.345.678-00', 'Ubirajara Lopes', 'M', '1979-04-29', '2021-02-20', '12345678920', 'ubirajara@example.com', 'Rua T,117'),
    (21, '123.456.789-22', 'Viviane Monteiro', 'F', '1980-09-30', '2021-03-21', '12345678921', 'viviane@example.com', 'Rua U, 118'),
    (22, '234.567.890-33', 'Wagner Silva', 'M', '1995-12-04', '2021-04-22', '12345678922', 'wagner@example.com', 'Rua V, 119'),
    (23, '345.678.901-44', 'Xavier Santos', 'M', '1985-07-17', '2021-05-23', '12345678923', 'xavier@example.com', 'Rua W, 120'),
    (24, '456.789.012-55', 'Yasmin Almeida', 'F', '1999-10-27', '2021-06-24', '12345678924', 'yasmin@example.com', 'Rua X, 121'),
    (25, '567.890.123-66', 'Zeca Souza', 'M', '1988-11-13', '2021-07-25', '12345678925', 'zeca@example.com', 'Rua Y, 122');

**Comment by paulos-f** [comment]
feito as inserções de de dados das tabelas.

**Comment by paulos-f** [comment]
INSERT INTO sinistro (cod_sinistro, cod_dispositivo, tp_sinistro, dt_sinistro) VALUES
    (26, 1, 1, '2022-01-10'),
    (27, 24, 2, '2018-06-20'),
    (28, 13, 3, '2019-03-25'),
    (29, 4, 4, '2017-04-30'),
    (30, 8, 1, '2019-11-01'),
    (31, 11, 2, '2018-12-05'),
    (32, 1, 3, '2017-06-10'),
    (33, 19, 4, '2019-08-15'),
    (34, 16, 5, '2017-09-25'),
    (35, 22, 1, '2018-10-05'),
    (36, 22, 2, '2017-02-14'),
    (37, 3, 3, '2018-03-01'),
    (38, 7, 4, '2017-04-05'),
    (39, 17, 5, '2019-05-10'),
    (40, 21, 1, '2018-06-15'),
    (41, 12, 2, '2017-07-20'),
    (42, 5, 3, '2019-08-25'),
    (43, 9, 4, '2018-10-30'),
    (44, 4, 5, '2019-11-10'),
    (45, 19, 1, '2018-12-15'),
    (46, 6, 2, '2017-01-20'),
    (47, 16, 3, '2019-03-25'),
    (48, 25, 4, '2017-05-30'),
    (49, 1, 5, '2018-06-05'),
    (50, 25, 1, '2019-01-10');
    
    INSERT INTO sinistro (cod_sinistro, cod_dispositivo, tp_sinistro, dt_sinistro) VALUES
    (51, 1, 1, '2017-02-14'),
    (52, 1, 1, '2018-05-20'),
    (53, 1, 3, '2019-11-11'),
    (54, 2, 2, '2017-07-25'),
    (55, 2, 1, '2018-09-30'),
    (56, 3, 4, '2017-12-05'),
    (57, 4, 1, '2018-01-15'),
    (58, 5, 5, '2019-08-20'),
    (59, 6, 1, '2017-03-11'),
    (60, 6, 1, '2018-12-15'),
    (61, 7, 3, '2019-04-20'),
    (62, 7, 1, '2017-11-05'),
    (63, 8, 2, '2018-06-25'),
    (64, 9, 4, '2019-02-10'),
    (65, 10, 1, '2017-09-14'),
    (66, 10, 5, '2018-05-30'),
    (67, 11, 1, '2019-03-25'),
    (68, 12, 1, '2017-08-18'),
    (69, 12, 3, '2018-10-10'),
    (70, 13, 1, '2019-07-14'),
    (71, 14, 2, '2017-04-25'),
    (72, 14, 2, '2018-07-05'),
    (73, 15, 4, '2019-06-22'),
    (74, 16, 1, '2017-05-30'),
    (75, 16, 3, '2018-09-10'),
    (76, 17, 1, '2019-11-19'),
    (77, 18, 5, '2017-01-21'),
    (78, 19, 2, '2018-04-15'),
    (79, 19, 4, '2019-12-10'),
    (80, 20, 1, '2017-06-11'),
    (81, 20, 3, '2018-02-20'),
    (82, 21, 1, '2019-05-29'),
    (83, 22, 4, '2017-10-23'),
    (84, 23, 1, '2018-11-12'),
    (85, 24, 2, '2019-09-09'),
    (86, 25, 1, '2017-07-13'),
    (87, 25, 1, '2018-08-04'),
    (88, 25, 3, '2019-01-18'),
    (89, 23, 1, '2017-12-24'),
    (90, 21, 4, '2018-06-16'),
    (91, 21, 5, '2019-03-04'),
    (92, 22, 1, '2017-09-19'),
    (93, 5, 1, '2018-10-29'),
    (94, 5, 3, '2019-07-06'),
    (95, 19, 1, '2017-08-14'),
    (96, 11, 2, '2018-09-28'),
    (97, 8, 4, '2019-05-16'),
    (98, 20, 1, '2017-05-03'),
    (99, 4, 3, '2018-11-23'),
    (100, 2, 1, '2019-04-12');

**Comment by brunoaiolfi** [comment]
corrigido pai 😳

**Comment by brunoaiolfi** [comment]
infelizmente tinha que fazer create por create, não achei nenhum método de create many no prisma
