### ISSUE TITLE
function

### ISSUE THREAD

**Issue by paulos-f** [paulos-f/Banco-2-o-Trabalho-Final#24]
função e chamada
    
    CREATE FUNCTION modelo_sinistro_causa ()
    RETURNS @resultado TABLE (
        nm_modelo VARCHAR(25),
        qtd_sinistros INT,
        causa_frequente VARCHAR(100)
    )
    AS
    BEGIN
        WITH SinistroData AS (
            SELECT 
                m.nm_modelo, 
                COUNT(s.cod_sinistro) AS qtd_sinistros,
                (SELECT TOP 1 ts.desc_sinistro
                 FROM sinistro s2
                 JOIN tipo_sinistro ts ON s2.tp_sinistro = ts.tp_sinistro
                 WHERE s2.cod_dispositivo = d.cod_dispositivo
                 GROUP BY ts.desc_sinistro
                 ORDER BY COUNT(s2.cod_sinistro) DESC) AS causa_frequente
            FROM sinistro s
            JOIN dispositivo d ON s.cod_dispositivo = d.cod_dispositivo
            JOIN modelo m ON d.cod_modelo = m.cod_modelo
            GROUP BY m.nm_modelo, d.cod_dispositivo
        )
        INSERT INTO @resultado
        SELECT 
            nm_modelo, 
            SUM(qtd_sinistros) AS qtd_sinistros, 
            causa_frequente
        FROM SinistroData
        GROUP BY nm_modelo, causa_frequente
        ORDER BY qtd_sinistros DESC;
        
        RETURN;
    END;
    
    SELECT *
    FROM modelo_sinistro_causa()
    ORDER BY qtd_sinistros DESC;

tem que verificar:

    ORDER BY qtd_sinistros DESC;

não ta funcionando. Por isso tive que fazer isso na chamada da função.

**Comment by kaiquedm12** [comment]
funçao para responder a 2 

    CREATE or alter FUNCTION dbo.fn_sinistros_por_plano_no_ultimo_ano()
    RETURNS TABLE
    AS
    RETURN
    (
        WITH sinistros_ultimo_ano AS (
            SELECT
                s.cod_plano,
                COUNT(si.cod_sinistro) AS total_sinistros
            FROM
                seguro s
                INNER JOIN sinistro si ON s.cod_dispositivo = si.cod_dispositivo
            WHERE
                si.dt_sinistro >= DATEADD(YEAR, -2, GETDATE())
            GROUP BY
                s.cod_plano
        ),
        cadastros_por_plano AS (
            SELECT
                s.cod_plano,
                COUNT(s.cod_seguro) AS total_cadastros
            FROM
                seguro s
            GROUP BY
                s.cod_plano
        )
        SELECT
            p.desc_plano,
            ISNULL(s.total_sinistros, 0) AS total_sinistros,
            c.total_cadastros,
            CASE
                WHEN c.total_cadastros > 0 THEN CAST(ISNULL(s.total_sinistros, 0) AS FLOAT) / c.total_cadastros
                ELSE 0
            END AS taxa_sinistros
        FROM
            plano p
            LEFT JOIN sinistros_ultimo_ano s ON p.cod_plano = s.cod_plano
            LEFT JOIN cadastros_por_plano c ON p.cod_plano = c.cod_plano
    );
    
    
    SELECT * FROM dbo.fn_sinistros_por_plano_no_ultimo_ano();

**Comment by kaiquedm12** [comment]
function para responder a 1
    
    CREATE FUNCTION modelo_sinistro_causa ()
    RETURNS @resultado TABLE (
        nm_modelo VARCHAR(25),
        qtd_sinistros INT,
        causa_frequente VARCHAR(100)
    )
    AS
    BEGIN
        WITH SinistroData AS (
            SELECT 
                m.nm_modelo, 
                COUNT(s.cod_sinistro) AS qtd_sinistros,
                (SELECT TOP 1 ts.desc_sinistro
                 FROM sinistro s2
                 JOIN tipo_sinistro ts ON s2.tp_sinistro = ts.tp_sinistro
                 WHERE s2.cod_dispositivo = d.cod_dispositivo
                 GROUP BY ts.desc_sinistro
                 ORDER BY COUNT(s2.cod_sinistro) DESC) AS causa_frequente
            FROM sinistro s
            JOIN dispositivo d ON s.cod_dispositivo = d.cod_dispositivo
            JOIN modelo m ON d.cod_modelo = m.cod_modelo
            GROUP BY m.nm_modelo, d.cod_dispositivo
        )
        INSERT INTO @resultado
        SELECT 
            nm_modelo, 
            SUM(qtd_sinistros) AS qtd_sinistros, 
            causa_frequente
        FROM SinistroData
        GROUP BY nm_modelo, causa_frequente
        ORDER BY qtd_sinistros DESC;
        
        RETURN;
    END;
    
    SELECT *
    FROM dbo.modelo_sinistro_causa()
    ORDER BY qtd_sinistros DESC;
