### ISSUE TITLE
Criando Trigger

### ISSUE THREAD

**Issue by kaiquedm12** [paulos-f/Banco-2-o-Trabalho-Final#25]
CREATE OR ALTER TRIGGER td_cliente ON cliente FOR INSERT AS

BEGIN

       IF ROWCOUNT_BIG() = 0
             RETURN
       SELECT GETDATE(), SUSER_NAME(), * FROM inserted
	   print('Novos dados de clientes inseridos ')
END

GO

talvez esteja muito simples irei tentar ajustar depois

**Comment by kaiquedm12** [comment]
CREATE OR ALTER TRIGGER td_cliente ON cliente FOR INSERT AS

BEGIN

       IF ROWCOUNT_BIG() = 0
             RETURN
       SELECT GETDATE()as horario, SUSER_NAME() as Usuario, * FROM inserted
	   print('Novos dados de clientes inseridos por ')
END

GO

**Comment by kaiquedm12** [comment]
create table historico_clien(
 [dt_inserção] date not null,
 [nm_usuario] varchar(100) not null,
 [cod_cliente] integer  not null,
  [cpf] varchar(11) not null,
  [nome] varchar(50) not null,
  [sexo] char,
  [dt_nascimento] date not null,
  [dt_cadastro] date not null,
  [num_contato] varchar(13) not null,
  [email] varchar(100),
  [endereco] varchar(100)

)

go

CREATE OR ALTER TRIGGER td_cliente ON cliente FOR INSERT AS

BEGIN

       IF ROWCOUNT_BIG() = 0
             RETURN
       INSERT INTO historico_clien

       SELECT GETDATE(), SUSER_NAME(), * FROM inserted
	   select * from historico_clien
	   print('Novos dados inseridos')
END

GO

**Comment by brunoaiolfi** [comment]
dei uma olhada ali e criei um de exemplo, só meter bala com base naquele
