### ISSUE TITLE
SELECT ou STORE PROCEDURE

### ISSUE THREAD

**Issue by JogadorZero** [paulos-f/Banco-2-o-Trabalho-Final#26]
Criar um SELECT ou STORE PROCEDURE para as perguntas de Negócio 3 e 4.

**Comment by JogadorZero** [comment]
Criar uma Store Procedure para resolver a pergunta de negócio 3.

**Comment by JogadorZero** [comment]
(André) Criar um SELECT para responder a pergunta de negócio 4.

**Comment by JogadorZero** [comment]
--Criada a resposta, com STORE PROCEDURE, para a pergunta de negócio 3.
--Irei reavaliar se está de acordo com a pergunta, e no próximo comentário irei finalizar.

/*
3- Existe alguma relação entre a idade do contrato e a frequência dos sinistros?
Os contratos mais antigos têm maior ou menor probabilidade de sinistros?
*/

GO
CREATE OR ALTER PROCEDURE pr_Relacao
AS
BEGIN
    -- Cria uma tabela temporária para armazenar os dados de idade do contrato e frequência de sinistros
    DECLARE @RelacaoIdadeFrequencia TABLE  (
        cod_seguro INTEGER,
        idade_contrato INTEGER,
        frequencia_sinistros INTEGER
    )

    -- Insere os dados na tabela temporária
    INSERT INTO @RelacaoIdadeFrequencia (cod_seguro, idade_contrato, frequencia_sinistros)
    SELECT 
        s.cod_seguro,
        DATEDIFF(YEAR, s.dt_inicio, GETDATE()) AS idade_contrato,
        COUNT(si.cod_sinistro) AS frequencia_sinistros
    FROM 
        seguro s
    LEFT JOIN 
        dispositivo d ON s.cod_dispositivo = d.cod_dispositivo
    LEFT JOIN 
        sinistro si ON d.cod_dispositivo = si.cod_dispositivo
    GROUP BY 
        s.cod_seguro, s.dt_inicio

    -- Seleciona os dados da tabela temporária
    SELECT * FROM @RelacaoIdadeFrequencia
	ORDER BY 
		frequencia_sinistros DESC

	DECLARE @resposta VARCHAR(1000)
	SET @resposta = 'Não existe relação entre a idade do contrato e a frequência dos sinistros, pois o tempo de contrato não influencia na quantidade de sinistros regisrados.'
	PRINT @resposta
END
GO

EXEC pr_Relacao
GO

**Comment by kaiquedm12** [comment]
Criar um SELECT para responder a pergunta de negócio 4.

    SELECT
        p.desc_plano,
        AVG(DATEDIFF(YEAR, c.dt_nascimento, GETDATE())) AS media_idade
    FROM
        seguro s
        inner JOIN cliente c ON s.cod_cliente = c.cod_cliente
        inner  JOIN plano p ON s.cod_plano = p.cod_plano
    GROUP BY
        p.desc_plano;

esta feita e funcionando
