### ISSUE TITLE
Atualização do trabalho (commits)

### ISSUE THREAD

**Issue by jlsilva01** [paulos-f/Banco-2-o-Trabalho-Final#3]
@paulos-f somente você atualizou o trabalho até este momento.
Sugiro revalidarem a distribução das tarefas para que tenha commits frequentes de todos da equipe neste repositório indicando o trabalho contínuo do mesmo.
Dúvida, me avisem.

**Comment by paulos-f** [comment]
Estávamos planejando o desenvolvimento do projeto ao longo da semana e decidimos fazer está primeira parte juntos hoje.
